apiVersion: v1
kind: Service
metadata:
  name: examples
  labels:
    app: examples
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: examples-ingress-proxy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: examples-ingress-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: examples-ingress-proxy
        version: v1
    spec:
      containers:
      - name: qdr-proxy
        command:
        - node
        - /opt/app-root/src/bin/proxy.js
        env:
        - name: QDP_DOMAIN
          value: -myproject.127.0.0.1.nip.io
        - name: SERVICE_NAME
          value: examples-ingress-proxy
        - name: SERVICE_VERSION
          value: v1
        - name: QDR_PROXY_PORT
          value: "8080"
        image: gordons/qdr-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      - name: jaeger-agent
        command:
        - /go/bin/agent-linux
        - --collector.host-port=jaeger-collector:14267
        image: jaegertracing/jaeger-agent
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
